apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testpod
  name: testpod
spec:
  containers:
  - image: surenmcode/redistest:1.3
    name: testpod
    resources: {}
    env:
    - name: CACHE_CRED
      valueFrom:
        secretKeyRef:
          name: redis
          key: cachekey
  dnsPolicy: ClusterFirst
  restartPolicy: Always  
status: {}
