apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: redisdemo
spec: {}
status: {}
---
apiVersion: v1
data:
  cachehost: akscache3.redis.cache.windows.net
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: redis
  namespace: redisdemo
---
apiVersion: v1
data:
  cachekey: Rzc4UWdPZlpRbUlxQkhFWm9rYVRXbWppRGhIRlVuYjZXU1E5SGVlZ3pOTT0= 
kind: Secret
metadata:
  creationTimestamp: null
  name: redis
  namespace: redisdemo
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testpod 
  name: testpod
  namespace: redisdemo
spec:
  nodeSelector:
    workloads: apps
  containers:
  - image: surenmcode/redisbench:1.0.15
    imagePullPolicy: Always
    name: redisbench 
    command: ["/bin/sh"]
    args: ["-c", "while true; do ./init.sh; sleep 10; done"]     
    resources: {}
    env:
    - name: CACHE_HOST
      valueFrom:
        configMapKeyRef:
          name: redis
          key: cachehost
    - name: CACHE_KEY
      valueFrom:
        secretKeyRef:
          name: redis
          key: cachekey
  - image: surenmcode/redisbench:1.0.15
    imagePullPolicy: Always
    name: redislatency
    resources: {}
    env:
    - name: CACHE_HOST
      valueFrom:
        configMapKeyRef:
          name: redis
          key: cachehost
    - name: CACHE_KEY
      valueFrom:
        secretKeyRef:
          name: redis
          key: cachekey
  dnsPolicy: ClusterFirst
  restartPolicy: Always  
status: {}
