apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: test
spec: {}
status: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: demopolicy
  namespace: test
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web
  name: web
  namespace: test
spec:
  containers:
  - image: nginx
    name: web
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tester
  name: tester
  namespace: test
spec:
  containers:
  - image: surenmcode/utils:alpine
    name: tester
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

