apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redistest
  name: redistest
  namespace: redisdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redistest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redistest
    spec:
      containers:
      - image: surenmcode/redistest:loop
        name: redistest      
        resources: {}
        env:
        - name: CACHE_CRED
          valueFrom:
            secretKeyRef:
              name: redis
              key: cachekey
status: {}
