apiVersion: v1
data:
  cachekey: QkhaZ3pWdXAwOCttVDFXaHh4RHU1MWxDeE5SR3FPU0c0a1ZVM3JKZEhIMD0=
kind: Secret
metadata:
  creationTimestamp: null
  name: redis
  namespace: redisdemo

# create secret generic redis --from-literal=cachekey=$CACHE_KEY -n redisdemo --dry-run -o yaml > secret.yaml